"""
Trade-related data models for the D.A.T.A. trading agent.

Defines structures for candidate trades, orders, and positions.
"""

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import uuid4

from pydantic import BaseModel, Field


class OrderType(str, Enum):
    """Order type classification."""

    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"
    TRAILING_STOP = "trailing_stop"
    MOC = "market_on_close"
    LOC = "limit_on_close"


class OrderStatus(str, Enum):
    """Order status."""

    PENDING = "pending"
    SUBMITTED = "submitted"
    PARTIAL = "partial"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class Side(str, Enum):
    """Trade side."""

    BUY = "buy"
    SELL = "sell"


class PositionSide(str, Enum):
    """Position side."""

    LONG = "long"
    SHORT = "short"
    FLAT = "flat"


class TradeTimeframe(str, Enum):
    """Trade timeframe classification."""

    SCALP = "scalp"  # Minutes
    INTRADAY = "intraday"  # Hours
    SWING = "swing"  # Days
    POSITION = "position"  # Weeks


class CandidateTrade(BaseModel):
    """
    A candidate trade generated by a strategy agent.

    This represents a trade idea before risk approval.
    """

    id: str = Field(default_factory=lambda: str(uuid4()))
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Core trade parameters
    symbol: str
    side: Side
    suggested_size: float  # Suggested position size (may be adjusted by risk)
    entry_price: Optional[float] = None  # None for market orders
    stop_loss: float  # Required - defines risk
    take_profit: Optional[float] = None

    # Trade classification
    timeframe: TradeTimeframe = TradeTimeframe.INTRADAY
    asset_class: str = "equities"

    # Strategy info
    strategy_name: str
    strategy_version: str = "1.0.0"
    signal_strength: float = 0.5  # 0-1 confidence score

    # Reasoning (for logging and review)
    entry_reason: str = ""
    setup_type: str = ""  # e.g., "breakout", "pullback", "reversal"

    # Features at time of signal (for ML feedback loop)
    features: dict[str, float] = Field(default_factory=dict)

    # Risk metrics (calculated)
    risk_amount: Optional[float] = None  # $ risk if stop hit
    risk_percent: Optional[float] = None  # % of portfolio at risk
    reward_risk_ratio: Optional[float] = None

    class Config:
        use_enum_values = True

    def calculate_risk_metrics(
        self, account_equity: float, entry_price: Optional[float] = None
    ) -> None:
        """Calculate risk metrics for this trade."""
        price = entry_price or self.entry_price
        if price is None or self.stop_loss is None:
            return

        # Calculate distance to stop
        if self.side == Side.BUY:
            stop_distance = price - self.stop_loss
        else:
            stop_distance = self.stop_loss - price

        if stop_distance <= 0:
            return  # Invalid stop placement

        # Risk per share/unit
        risk_per_unit = abs(stop_distance)

        # Total risk
        self.risk_amount = risk_per_unit * self.suggested_size
        self.risk_percent = (self.risk_amount / account_equity) * 100 if account_equity > 0 else 0

        # Reward/risk ratio
        if self.take_profit is not None:
            if self.side == Side.BUY:
                reward = self.take_profit - price
            else:
                reward = price - self.take_profit

            self.reward_risk_ratio = reward / risk_per_unit if risk_per_unit > 0 else 0


class Order(BaseModel):
    """An order to be submitted to a broker/exchange."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Link to candidate trade
    candidate_trade_id: Optional[str] = None

    # Order parameters
    symbol: str
    side: Side
    quantity: float
    order_type: OrderType = OrderType.MARKET
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    time_in_force: str = "day"  # day, gtc, ioc, fok

    # Status
    status: OrderStatus = OrderStatus.PENDING
    broker_order_id: Optional[str] = None

    # Execution details
    filled_quantity: float = 0.0
    average_fill_price: Optional[float] = None
    commission: float = 0.0
    slippage: Optional[float] = None

    # Timestamps
    submitted_at: Optional[datetime] = None
    filled_at: Optional[datetime] = None
    cancelled_at: Optional[datetime] = None

    # Error handling
    reject_reason: Optional[str] = None
    error_message: Optional[str] = None

    # Metadata
    strategy_name: Optional[str] = None
    tags: list[str] = Field(default_factory=list)

    class Config:
        use_enum_values = True

    @property
    def is_complete(self) -> bool:
        """Check if order is in a terminal state."""
        return self.status in [
            OrderStatus.FILLED,
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
            OrderStatus.EXPIRED,
        ]

    @property
    def remaining_quantity(self) -> float:
        """Get unfilled quantity."""
        return self.quantity - self.filled_quantity

    def calculate_slippage(self, expected_price: float) -> None:
        """Calculate slippage from expected price."""
        if self.average_fill_price is not None:
            if self.side == Side.BUY:
                self.slippage = self.average_fill_price - expected_price
            else:
                self.slippage = expected_price - self.average_fill_price


class Position(BaseModel):
    """A current position in an instrument."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    opened_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Position details
    symbol: str
    side: PositionSide
    quantity: float
    average_entry_price: float

    # Risk management
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop_distance: Optional[float] = None

    # Current state
    current_price: Optional[float] = None
    unrealized_pnl: float = 0.0
    unrealized_pnl_percent: float = 0.0

    # Peak metrics for MFE/MAE calculation
    max_favorable_excursion: float = 0.0  # Best unrealized PnL reached
    max_adverse_excursion: float = 0.0  # Worst unrealized PnL reached

    # Strategy info
    strategy_name: Optional[str] = None
    timeframe: TradeTimeframe = TradeTimeframe.INTRADAY
    entry_order_ids: list[str] = Field(default_factory=list)

    # Closed position fields
    closed_at: Optional[datetime] = None
    exit_price: Optional[float] = None
    realized_pnl: float = 0.0
    realized_pnl_percent: float = 0.0
    exit_reason: Optional[str] = None  # stop_loss, take_profit, manual, signal

    # Costs
    total_commission: float = 0.0
    total_slippage: float = 0.0

    class Config:
        use_enum_values = True

    @property
    def is_open(self) -> bool:
        """Check if position is still open."""
        return self.closed_at is None and self.quantity > 0

    @property
    def market_value(self) -> float:
        """Calculate current market value."""
        price = self.current_price or self.average_entry_price
        return self.quantity * price

    @property
    def cost_basis(self) -> float:
        """Calculate cost basis."""
        return self.quantity * self.average_entry_price

    def update_price(self, price: float) -> None:
        """Update current price and recalculate PnL."""
        self.current_price = price
        self.updated_at = datetime.utcnow()

        # Calculate unrealized PnL
        if self.side == PositionSide.LONG:
            self.unrealized_pnl = (price - self.average_entry_price) * self.quantity
        else:  # SHORT
            self.unrealized_pnl = (self.average_entry_price - price) * self.quantity

        self.unrealized_pnl_percent = (
            (self.unrealized_pnl / self.cost_basis) * 100 if self.cost_basis > 0 else 0
        )

        # Update MFE/MAE
        if self.unrealized_pnl > self.max_favorable_excursion:
            self.max_favorable_excursion = self.unrealized_pnl
        if self.unrealized_pnl < self.max_adverse_excursion:
            self.max_adverse_excursion = self.unrealized_pnl

    def should_stop_out(self) -> bool:
        """Check if stop loss should trigger."""
        if self.stop_loss is None or self.current_price is None:
            return False

        if self.side == PositionSide.LONG:
            return self.current_price <= self.stop_loss
        else:  # SHORT
            return self.current_price >= self.stop_loss

    def should_take_profit(self) -> bool:
        """Check if take profit should trigger."""
        if self.take_profit is None or self.current_price is None:
            return False

        if self.side == PositionSide.LONG:
            return self.current_price >= self.take_profit
        else:  # SHORT
            return self.current_price <= self.take_profit


class PortfolioSnapshot(BaseModel):
    """Snapshot of the entire portfolio at a point in time."""

    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Account info
    total_equity: float
    cash: float
    margin_used: float = 0.0
    buying_power: float = 0.0

    # Positions
    positions: list[Position] = Field(default_factory=list)
    open_orders: list[Order] = Field(default_factory=list)

    # Aggregate metrics
    total_unrealized_pnl: float = 0.0
    total_realized_pnl_today: float = 0.0
    daily_pnl: float = 0.0
    daily_pnl_percent: float = 0.0

    # Risk metrics
    total_exposure: float = 0.0  # Sum of position values
    net_exposure: float = 0.0  # Long - Short exposure
    gross_exposure_percent: float = 0.0
    portfolio_heat: float = 0.0  # Sum of open risk (to stops)

    # Concentration
    largest_position_percent: float = 0.0
    sector_exposures: dict[str, float] = Field(default_factory=dict)

    @property
    def num_positions(self) -> int:
        """Number of open positions."""
        return len([p for p in self.positions if p.is_open])

    @property
    def long_exposure(self) -> float:
        """Total long exposure."""
        return sum(
            p.market_value for p in self.positions if p.is_open and p.side == PositionSide.LONG
        )

    @property
    def short_exposure(self) -> float:
        """Total short exposure."""
        return sum(
            p.market_value for p in self.positions if p.is_open and p.side == PositionSide.SHORT
        )
